name: build_android_full (2)

on:
  workflow_dispatch:

jobs:
  build:
    name: build appbundle production-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
      #      - run: flutter test
      - run: flutter build appbundle --release --flavor production -t lib/main_production.dart

      - name: Upload APPBUNDLE
        uses: actions/upload-artifact@v3
        with:
          name: android-production-release.aab
          path: build/app/outputs/bundle/productionRelease/app-production-release.aab
##          path: build\app\outputs\bundle\productionRelease\app-production-release.aab



  deploy-play-store:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # 1
      - uses: actions/download-artifact@v3
        with:
          name: android-production-release.aab
      #      - uses: actions/download-artifact@master
      #        with:
      #          name: mapping.txt
      # 2
      - name: Publish to Play Store internal test track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          # 3
          packageName: com.startingfinace.scrumpoker
#          releaseFile: android-production-release.aab
          releaseFile: build/app/outputs/bundle/productionRelease/app-production-release.aab
          track: internal
          userFraction: 0.50
#          mappingFile: mapping.txt
