name: Android Step 3 - deploy app bundle to Play Store

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  deploy-play-store:
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: android_signing_production_release.yml
          name: android-production-release-signed.aab
          path: signed/
      - name: Publish to Play Store internal test track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: com.startingfinace.scrumpoker
          releaseFiles: signed/app-production-release.aab
          track: internal
          status: completed
