# This is a basic workflow to help you get started with Actions
name: BuildApkDebug

# Controls when the workflow will run
on:
  workflow_dispatch:
#  push:
#    tags:
#      - '*'

jobs:
  releases:
    name: build apk debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
#      - run: flutter test
      - run: flutter build apk --debug --flavor flavor_dev

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: build/app/outputs/flutter-apk/app-dev-debug.apk
