name: Build_Apk_Production_Debug

on:
  workflow_dispatch:

jobs:
  releases:
    name: build apk production-debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
      #      - run: flutter test
      - run: flutter build apk --debug --flavor production -t lib/main_production.dart

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: android-production-debug.apk
          path: build/app/outputs/flutter-apk/app-production-debug.apk
