# This is a basic workflow to help you get started with Actions
name: Build_Apk_Dev_Debug

# Controls when the workflow will run
on:
  workflow_dispatch:
#  push:
#    tags:
#      - '*'


jobs:
  releases:
    name: build apk debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
#      - run: flutter test
      - run: flutter build apk --debug --flavor flavor_dev --dart-define=flavor="dev"

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: dev-debug-apk
          path: build/app/outputs/flutter-apk/app-flavor_dev-debug.apk
