name: Build_Apk_Prod_Releases

on:
  workflow_dispatch:
#  push:
#    tags:
#      - '*'

jobs:
  releases:
    name: build apk prod-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
#      - run: flutter test
      - run: flutter build apk --release --flavor flavor_prod --dart-define=flavor="prod"

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: prod-release-apk
          path: build/app/outputs/flutter-apk/app-flavor_prod-release.apk
