name: Build_Apk_Dev_Releases

on:
  workflow_dispatch:
#  push:
exit#    tags:
#      - '*'

jobs:
  releases:
    name: build apk dev-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
      #      - run: flutter test
      - run: flutter build apk --release --flavor flavor_dev --dart-define=flavor="dev"

      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: dev-release-apk
          path: build/app/outputs/flutter-apk/app-flavor_dev-release.apk
