name: Deploy to Play Store V.010

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  deploy-play-store:
    runs-on: ubuntu-latest
    steps:
      # 1
       - name: Publish to Play Store internal test track
         uses: r0adkll/upload-google-play@v1
         with:
           serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
           # 3
           packageName: com.startingfinace.scrumpoker
           releaseFile: Documenti/android-production-release.aab
 #           releaseFile: build/app/outputs/bundle/productionRelease/app-production-release.aab
           track: internal
           userFraction: 0.50
 #          mappingFile: mapping.txt
