name: Deploy to Play Store V.002

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#      - name: Generate Release APK
#        run: ./gradlew assembleRelease
#      - name: Sign APK
#        uses: r0adkll/sign-android-release@v1
#        # ID used to access action output
#        id: sign_app
#        with:
#          releaseDirectory: app/build/outputs/apk/release
#          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
#          alias: ${{ secrets.ALIAS }}
#          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
#          keyPassword: ${{ secrets.KEY_PASSWORD }}
#      - uses: actions/upload-artifact@master
#        with:
#          name: release.apk
#          path: ${{steps.sign_app.outputs.signedReleaseFile}}
#      - uses: actions/upload-artifact@master
#        with:
#          name: mapping.txt
#          path: app/build/outputs/mapping/release/mapping.txt

  deploy-play-store:
#    needs: [build]
    runs-on: ubuntu-latest
    steps:
      # 1
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: build_appbundle_production_release.yml
          name: android-production-release.aab
#      - uses: actions/download-artifact@master
#        with:
#          name: android-production-release.aab
#      - uses: actions/download-artifact@master
#        with:
#          name: mapping.txt
      # 2
      - name: Publish to Play Store internal test track
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          # 3
          packageName: com.startingfinace.scrumpoker
#          releaseFile: android-production-release.aab
          releaseFile: build/app/outputs/bundle/productionRelease/app-production-release.aab
          track: internal
          userFraction: 0.50
#          mappingFile: mapping.txt
