name: Deploy to Play Store V.014

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  deploy-play-store:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v3

      # 1
       - run: echo  ${GITHUB_WORKSPACE}
       - run: ls -l /home/runner/work/ScrumPoker/ScrumPoker/Documenti
       - name: Publish to Play Store internal test track
         uses: r0adkll/upload-google-play@v1
         with:
           serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
           # 3
           packageName: com.startingfinace.scrumpoker
           releaseFile: '/home/runner/work/ScrumPoker/ScrumPoker/Documenti/android-production-release.aab'
 #           releaseFile: build/app/outputs/bundle/productionRelease/app-production-release.aab
           track: internal
           userFraction: 0.50
 #          mappingFile: mapping.txt
