name: iOS.2 - Sign Automatic (1)

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Current folder
        run: pwd

      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64_DISTRIBUTION_APPLE }}
          p12-password: ${{ secrets.P12_PASSWORD_DISTRIBUTION_APPLE }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_DISTRIBUTION_BASE64_APPLE }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles



      - name: Download Runner.app
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ios-build-automatic.yml
          name: ios-release-production-no-codesign-automatic.app
          path: build/ios/iphoneos/

      - name: Build xArchive Automatic
        run: |
          xcodebuild \
          -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -sdk 'iphoneos' \
          -destination 'generic/platform=iOS' \
          -configuration Release \
          -archivePath build-output/app.xcarchive \
          -resolvePackageDependencies \
          clean \
          archive

      - name: Export ipa
        run: xcodebuild -exportArchive -archivePath build-output/app.xcarchive -exportPath build-output/ios -exportOptionsPlist ios/ExportOptions.plist

#  - name: Build xArchive
#    run: |
#      xcodebuild -workspace ios/Runner.xcworkspace
#      -scheme Runner
#      -configuration Release DEVELOPMENT_TEAM=YOUR_TEAM_ID
#      -sdk 'iphoneos'
#      -destination 'generic/platform=iOS'
#      -archivePath build-output/app.xcarchive PROVISIONING_PROFILE=YOUR_UUID clean archive CODE_SIGN_IDENTITY="Apple Distribution: Damien Aicheh"

# List Folder

#      - name: List
#        run: ls -R