name: iOS Step 2 - Sign (3)

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2


      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64_DISTRIBUTION_APPLE }}
          p12-password: ${{ secrets.P12_PASSWORD_DISTRIBUTION_APPLE }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_DISTRIBUTION_BASE64_APPLE }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles



      - name: Download Runner.app
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ios-build.yml
          name: ios-release-production-no-codesign.app
          path: build/ios/iphoneos/

      - name: Build xArchive
        run: |
          xcodebuild \
          -workspace ios/Runner.xcworkspace \
          -scheme Runner \
          -configuration Release \
          -archivePath build-output/app.xcarchive \
          -resolvePackageDependencies
      #\\\         DEVELOPMENT_TEAM='ZS99A4QXZW'

      - name: Upload app.xcarchive
        uses: actions/upload-artifact@v1
        with:
          name: app.xcarchive
          path: build-output/app.xcarchive
