name: Flutter_iOS

on:
  workflow_dispatch:

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2


      - name: Install Apple Certificate
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.BUILD_CERTIFICATE_BASE64_DISTRIBUTION_APPLE }}
          p12-password: ${{ secrets.P12_PASSWORD_DISTRIBUTION_APPLE }}

      - name: Install the provisioning profile
        env:
          PROVISIONING_CERTIFICATE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_DISTRIBUTION_BASE64_APPLE }}
        run: |
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision

          echo -n "$PROVISIONING_CERTIFICATE_BASE64" | base64 --decode --output $PP_PATH

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

#      - name: Install and set Flutter version
#        uses: subosito/flutter-action@v2
#        with:
#          flutter-version: '3.0.1'
#
#      - name: Restore packages
#        run: flutter pub get
#
#      - name: Build Flutter
#        run: flutter build ios --release --flavor production -t lib/main_production.dart --no-codesign

      - name: Build resolve Swift dependencies
        run: xcodebuild -resolvePackageDependencies -workspace ios/Runner.xcworkspace -scheme Runner -configuration Release
