name: Say hello 2

on:
  workflow_call:
    inputs:
      my_name:
        required: true
        type: string

jobs:
  reusable_workflow_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "hello ${{ github.event.inputs.my_name }}"