name: Say hello bob

on:
  workflow_dispatch:

jobs:
  deploy-play-store:
    runs-on: ubuntu-latest
    steps:
      - name: say_hello_bob
        uses: ./.github/workflows/say_hello.yml
        with:
          my_name: Bob01
